# Generated by Django 4.1.6 on 2023-02-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
                ('news_datetime', models.DateTimeField(verbose_name='Published at')),
                ('news_headline', models.TextField(blank=True, null=True, verbose_name='News Headline')),
                ('news_id', models.IntegerField(blank=True, null=True, verbose_name='News ID')),
                ('news_image', models.CharField(blank=True, max_length=256, null=True, verbose_name='News Image')),
                ('news_ticker_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='Ticker')),
                ('news_source', models.CharField(blank=True, max_length=256, null=True, verbose_name='News Source')),
                ('news_summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('news_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='News URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Company News',
            },
        ),
    ]
