# Generated by Django 4.1.6 on 2023-02-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynews',
            options={'verbose_name': 'Company News', 'verbose_name_plural': 'Company News'},
        ),
    ]
