# Generated by Django 4.1.6 on 2023-02-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_companynews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynews',
            options={'verbose_name': 'Company Article', 'verbose_name_plural': 'Company News'},
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Article Category'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_headline',
            field=models.TextField(blank=True, null=True, verbose_name='Article Headline'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Article ID'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_image',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Article Image'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_source',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Article Source'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Article Summary'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Article URL'),
        ),
    ]
