# Generated by Django 4.1.6 on 2023-02-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_companynews_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='news_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Article Image'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_source',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Article Source'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Article URL'),
        ),
    ]
